### ISSUE TITLE
Doesn't pull data from main library

### ISSUE THREAD

**Issue by hancooo** [NemesisRE/sensor.plex_recently_added#2]
Pulling from random library instead of main library. 
In plex I have 3 libraries for movies (All Movies, Kids Movies & Marvel MCU Movies). The kids and marvel are just sym links, the main library (All Movies) is the one that reguarly gets the new content added. 

Your component first picked the most recent film in Kids instead of main (Raya and the last dragon), I excluded Raya to try and push on to the next and then it just picked the latest in Marvel (Thor film). 

Is there a way to select a specific library within your config? 

![image](https://user-images.githubusercontent.com/20757683/194947990-b33e6de3-06eb-4f4a-9b89-388cb8ed20f8.png)

![image](https://user-images.githubusercontent.com/20757683/194948339-93bd66eb-ffe9-44a0-a89e-a6615202c2dd.png)

![image](https://user-images.githubusercontent.com/20757683/194948360-e9ee4946-4771-4c56-a6d9-d608bcc8c152.png)

![image](https://user-images.githubusercontent.com/20757683/194948392-90ae4d4d-6c35-4039-8ddc-32339640a1e5.png)

Home Assistant version: 2022.10.2

```
  - platform: plex_recently_added
    name: Recently Added Movies  
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    max: 4
    img_dir: /
    image_resolution: 800
    section_types:
      - movie
    exclude_keywords:
      - Raya and
```
