### ISSUE TITLE
Add metadata key in card_item

### ISSUE THREAD

**Issue by manu3b1** [NemesisRE/sensor.plex_recently_added#4]
Now that Apple TV integration supports [Deep Links](https://www.home-assistant.io/integrations/apple_tv/#launching-apps), would be great to add metadata key in card_item as this is the only way go build a working Plex deep link, like this one:

```
- variables:
    serverId: "xxxxxxxxxxxxxxxx"
    episodes: "{{ state_attr('sensor.plex_recently_added', 'data') }}"
    key: "{{ episodes[1].key }}"
- service: media_player.play_media
  data:
    media_content_type: url
    media_content_id: plex://play/?metadataKey=%2Flibrary%2Fmetadata%2F{{key}}&metadataType=4&server={{serverId}}
  target:
    entity_id: media_player.mon_apple_tv
```

I've tested a patch in sensor.py that works well:

```
                 card_item = {}
                 if 'ratingKey' in media:
                     key = media['ratingKey']
+                    card_item['key'] = media.get('ratingKey', '')
                 else:
                     continue
                 if 'addedAt' in media:
```

The big interest of Plex deep links thru Apple TV media_player is that they are much more reliable than Plex media_player integration, where the connection between server and client is hazardous.
