### ISSUE TITLE
GUID for deeplink [Feature Request]

### ISSUE THREAD

**Issue by theNorr** [NemesisRE/sensor.plex_recently_added#6]
**Is your feature request related to a problem? Please describe.**
No. I'd like for this integration to grab and display the movie or series GUID as well.

**Describe the solution you'd like**
With that you'd be able to set up an automation that forwards the deeplink to that movie or episode in a notification to your phone.

**Describe alternatives you've considered**
I don't know enough to find any alternatives and Google wasn't very helpful. I'd be happy with a deeplink that just takes me to the plex-app as well.

**Comment by mkanet** [comment]
Do you mean like below?  I modified my local copy of this integration on Home Assistant.  If this is what you want, I can fork this repo with this new enhancement.  Just let me know.

**Recently Added Movies:**
![image](https://github.com/NemesisRE/sensor.plex_recently_added/assets/811008/fe4b899c-2da9-4181-8fbf-28ec1ddda879)

**Recently Added TV:**
![image](https://github.com/NemesisRE/sensor.plex_recently_added/assets/811008/17882095-3fa1-4725-8bac-2d32348b8615)

**PS:**  On a related note... I also recently enhanced [upcoming-media-card](https://github.com/custom-cards/upcoming-media-card).  My version adds a new `url:` setting to the card options to make respective cards clickable (or touchable on a portable device).  Clicking on the card will take you to your Sonarr/Radarr URL or whatever URL you want.  I will make this available to you as well, if you wish.  I haven't uploaded my code enhancements yet to github.

For example:
```yaml
type: custom:upcoming-media-card
entity: sensor.recently_added_tv
accent_color: '#222222'
border_color: '#222222'
box_shadows: false
image_style: fanart
title: TV
line1_color: '#BCBCBC'
line2_color: '#BCBCBC'
line3_color: '#BCBCBC'
line4_color: '#BCBCBC'
url: https://sonarr.mkanet.dynip.com
```
or
```yaml
title: Movies
type: custom:upcoming-media-card
entity: sensor.recently_added_movies
accent_color: '#222222'
border_color: '#222222'
box_shadows: false
image_style: fanart
url: https://radarr.mkanet.dynip.com
```

**Comment by mkanet** [comment]
@theNorr do you mean like below?  I modified my existing local plex_recently_added integration to do this.  If this is what you want, I can fork this repo with the new deep_link feature.  If I copy the generated deep_link URL from the attributes below in a web browser, it will take me directly to the specific Episode or Movie in the Plex web interface.  Hopefully, this is what you want.

`sensor.recently_added_movies`

State: Online

Attributes:
```
data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $number - $rating - $runtime
    line4_default: $genres
    icon: mdi:eye-off
  - airdate: "2024-01-21T20:24:59Z"
    aired: "2024-01-08"
    release: $day, $date $time
    flag: true
    title: The Beekeeper
    episode: ""
    deep_link: >-
      http://192.168.1.2:32400/web/index.html#!/server/fse4033530953929f92439334395935g9d39211c/details?key=%2Flibrary%2Fmetadata%2F8357
    runtime: 168
    studio: Miramax
    genres: Action, Thriller
    rating: ""
    poster: /local/plex_artwork/Recently_Added_Movies/p8357.jpg
    fanart: /local/plex_artwork/Recently_Added_Movies/f8357.jpg
  - airdate: "2024-01-12T08:26:29Z"
    aired: "2024-01-12"
    release: $day, $date $time
    flag: true
    title: Lift
    episode: ""
    deep_link: >-
      http://192.168.1.2:32400/web/index.html#!/server/fse4033530953929f92439334395935g9d39211c/details?key=%2Flibrary%2Fmetadata%2F8076
    runtime: 106
    studio: Genre Films
    genres: Action, Crime
    rating: ""
    poster: /local/plex_artwork/Recently_Added_Movies/p8076.jpg
    fanart: /local/plex_artwork/Recently_Added_Movies/f8076.jpg
  - airdate: "2024-01-08T14:46:25Z"
    aired: "2023-11-22"
    release: $day, $date $time
    flag: true
    title: Napoleon
    episode: ""
    deep_link: >-
      http://192.168.1.2:32400/web/index.html#!/server/fse4033530953929f92439334395935g9d39211c/details?key=%2Flibrary%2Fmetadata%2F8063
    runtime: 157
    studio: Scott Free Productions
    genres: Action, Adventure
    rating: ""
    poster: /local/plex_artwork/Recently_Added_Movies/p8063.jpg
    fanart: /local/plex_artwork/Recently_Added_Movies/f8063.jpg
  - airdate: "2024-01-04T03:51:32Z"
    aired: "2007-02-15"
    release: $day, $date $time
    flag: true
    title: Bridge to Terabithia
    episode: ""
    deep_link: >-
      http://192.168.1.2:32400/web/index.html#!/server/fse4033530953929f92439334395935g9d39211c/details?key=%2Flibrary%2Fmetadata%2F8019
    runtime: 95
    studio: Lauren Levine Productions Inc.
    genres: Adventure, Drama
    rating: ""
    poster: /local/plex_artwork/Recently_Added_Movies/p8019.jpg
    fanart: /local/plex_artwork/Recently_Added_Movies/f8019.jpg
  - airdate: "2023-12-30T04:55:23Z"
    aired: "2023-09-13"
    release: $day, $date $time
    flag: false
    title: The Burial
    episode: ""
    deep_link: >-
      http://192.168.1.2:32400/web/index.html#!/server/fse4033530953929f92439334395935g9d39211c/details?key=%2Flibrary%2Fmetadata%2F7976
    runtime: 127
    studio: Double Nickel Entertainment
    genres: Drama, History
    rating: ""
    poster: /local/plex_artwork/Recently_Added_Movies/p7976.jpg
    fanart: /local/plex_artwork/Recently_Added_Movies/f7976.jpg
friendly_name: Recently Added Movies
```
**Recently added Movies:**
![image](https://github.com/NemesisRE/sensor.plex_recently_added/assets/811008/83d574f3-57c9-44ba-89c7-1fcc94cb9810)

**Recently added TV:**
![image](https://github.com/NemesisRE/sensor.plex_recently_added/assets/811008/4eadd480-275d-4017-b60a-f7c535f228d2)
